import { mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";
import type { GeneratorsConfig } from "@frond/config";

export interface GenerateOptions {
  rootDir: string;
  openApiPath: string;
  generators: GeneratorsConfig;
  group?: string;
}

interface Op {
  method: string;
  path: string;
  operationId: string;
  summary: string;
  hasBody: boolean;
}

function toCamel(id: string): string {
  const cleaned = id.replace(/[^a-zA-Z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  const parts = cleaned.split("_").filter(Boolean);
  if (parts.length === 0) return "operation";
  return parts[0]!.toLowerCase() + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join("");
}

function toSnake(id: string): string {
  return toCamel(id)
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}

function pathToTemplate(p: string, lang: "ts" | "py"): string {
  if (lang === "ts") {
    return p.replace(/\{([^}]+)\}/g, "${encodeURIComponent(String(params.$1))}");
  }
  return p.replace(/\{([^}]+)\}/g, "{params['$1']}");
}

function pathParams(p: string): string[] {
  return [...p.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]!);
}

async function loadOperations(openApiPath: string): Promise<{ title: string; ops: Op[] }> {
  const raw = await readFile(openApiPath, "utf-8");
  const spec = (openApiPath.endsWith(".json") ? JSON.parse(raw) : YAML.parse(raw)) as {
    info?: { title?: string };
    paths?: Record<string, Record<string, { operationId?: string; summary?: string; requestBody?: unknown }>>;
  };
  const ops: Op[] = [];
  for (const [p, methods] of Object.entries(spec.paths ?? {})) {
    for (const [method, op] of Object.entries(methods)) {
      if (!["get", "post", "put", "patch", "delete", "head", "options"].includes(method.toLowerCase())) continue;
      const operationId = op.operationId || `${method}_${p.replace(/[^a-zA-Z0-9]+/g, "_")}`;
      ops.push({
        method: method.toUpperCase(),
        path: p,
        operationId,
        summary: op.summary || operationId,
        hasBody: Boolean(op.requestBody) || ["POST", "PUT", "PATCH"].includes(method.toUpperCase()),
      });
    }
  }
  return { title: spec.info?.title ?? "API", ops };
}

export async function generateSDKs(options: GenerateOptions): Promise<string[]> {
  const groupName = options.group ?? options.generators["default-group"];
  const group = options.generators.groups[groupName];
  if (!group) throw new Error(`Generator group '${groupName}' not found`);

  const { ops } = await loadOperations(options.openApiPath);
  const generated: string[] = [];

  for (const gen of group.generators) {
    const outDir = path.resolve(options.rootDir, gen.output.path);
    await mkdir(outDir, { recursive: true });

    if (gen.name === "frond/typescript-sdk") {
      await generateTypeScriptSDK(outDir, options.openApiPath, ops);
      generated.push(outDir);
    } else if (gen.name === "frond/python-sdk") {
      await generatePythonSDK(outDir, options.openApiPath, ops);
      generated.push(outDir);
    } else {
      throw new Error(`Unknown generator: ${gen.name}`);
    }
  }

  return generated;
}

async function generateTypeScriptSDK(outDir: string, openApiPath: string, ops: Op[]) {
  const methods = ops
    .map((op) => {
      const name = toCamel(op.operationId);
      const params = pathParams(op.path);
      const pathExpr = "`" + pathToTemplate(op.path, "ts") + "`";
      const args: string[] = [];
      if (params.length) args.push(`params: { ${params.map((p) => `${p}: string | number`).join("; ")} }`);
      if (op.hasBody) args.push("body?: unknown");
      const argList = args.join(", ");
      const bodyArg = op.hasBody ? ", body" : "";
      return `  /** ${op.summary} */\n  ${name}(${argList}): Promise<unknown> {\n    return this.request("${op.method}", ${params.length ? pathExpr : JSON.stringify(op.path)}${bodyArg});\n  }`;
    })
    .join("\n\n");

  const clientCode = `/**
 * Generated by Frond — do not edit manually.
 * Source: ${path.basename(openApiPath)}
 * Operations: ${ops.length}
 */

export interface FrondClientOptions {
  baseUrl: string;
  apiKey?: string;
  bearerToken?: string;
}

export class FrondClient {
  constructor(private readonly options: FrondClientOptions) {}

  private headers(): HeadersInit {
    const h: Record<string, string> = {
      "Content-Type": "application/json",
      Accept: "application/json",
    };
    if (this.options.bearerToken) h.Authorization = \`Bearer \${this.options.bearerToken}\`;
    if (this.options.apiKey) h["X-Api-Key"] = this.options.apiKey;
    return h;
  }

  async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await fetch(new URL(path, this.options.baseUrl), {
      method,
      headers: this.headers(),
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new Error(\`API error \${res.status}: \${await res.text()}\`);
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

${methods || "  // No operations found in OpenAPI"}
}
`;

  await writeFile(path.join(outDir, "client.ts"), clientCode);
  await writeFile(path.join(outDir, "index.ts"), `export * from "./client.js";\n`);
  await writeFile(
    path.join(outDir, "package.json"),
    JSON.stringify({ name: "@generated/frond-typescript-sdk", version: "0.1.0", type: "module", main: "./index.ts" }, null, 2),
  );
}

async function generatePythonSDK(outDir: string, openApiPath: string, ops: Op[]) {
  const methods = ops
    .map((op) => {
      const name = toSnake(op.operationId);
      const params = pathParams(op.path);
      const pyPath = pathToTemplate(op.path, "py");
      const args = ["self"];
      if (params.length) args.push("params: dict[str, Any]");
      if (op.hasBody) args.push("json: Any | None = None");
      const callArgs = op.hasBody ? ", json=json" : "";
      const pathExpr = params.length ? `f"${pyPath}"` : `"${op.path}"`;
      return `    def ${name}(${args.join(", ")}) -> Any:\n        """${op.summary}"""\n        return self.request("${op.method}", ${pathExpr}${callArgs})`;
    })
    .join("\n\n");

  const clientCode = `"""Generated by Frond — do not edit manually. Source: ${path.basename(openApiPath)}"""

from __future__ import annotations
from typing import Any, Optional
import httpx


class FrondClient:
    def __init__(self, base_url: str, api_key: Optional[str] = None, bearer_token: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.bearer_token = bearer_token

    def _headers(self) -> dict[str, str]:
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if self.bearer_token:
            headers["Authorization"] = f"Bearer {self.bearer_token}"
        if self.api_key:
            headers["X-Api-Key"] = self.api_key
        return headers

    def request(self, method: str, path: str, json: Any | None = None) -> Any:
        with httpx.Client(base_url=self.base_url, headers=self._headers(), timeout=30.0) as client:
            response = client.request(method, path, json=json)
            response.raise_for_status()
            if response.status_code == 204:
                return None
            return response.json()

${methods || "    pass"}
`;

  await writeFile(path.join(outDir, "client.py"), clientCode);
  await writeFile(path.join(outDir, "__init__.py"), `from .client import FrondClient\n`);
  await writeFile(
    path.join(outDir, "pyproject.toml"),
    `[project]\nname = "frond-python-sdk"\nversion = "0.1.0"\ndependencies = ["httpx>=0.27"]\n`,
  );
}
