import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { GeneratorsConfig } from "@frond/config";

export interface GenerateOptions {
  rootDir: string;
  openApiPath: string;
  generators: GeneratorsConfig;
  group?: string;
}

export async function generateSDKs(options: GenerateOptions): Promise<string[]> {
  const groupName = options.group ?? options.generators["default-group"];
  const group = options.generators.groups[groupName];
  if (!group) {
    throw new Error(`Generator group '${groupName}' not found`);
  }

  const generated: string[] = [];

  for (const gen of group.generators) {
    const outDir = path.resolve(options.rootDir, gen.output.path);
    await mkdir(outDir, { recursive: true });

    if (gen.name === "frond/typescript-sdk") {
      await generateTypeScriptSDK(outDir, options.openApiPath);
      generated.push(outDir);
    } else if (gen.name === "frond/python-sdk") {
      await generatePythonSDK(outDir, options.openApiPath);
      generated.push(outDir);
    } else {
      throw new Error(`Unknown generator: ${gen.name}`);
    }
  }

  return generated;
}

async function generateTypeScriptSDK(outDir: string, openApiPath: string) {
  const clientCode = `/**
 * Generated by Frond — do not edit manually.
 * Source: ${path.basename(openApiPath)}
 */

export interface FrondClientOptions {
  baseUrl: string;
  apiKey?: string;
  bearerToken?: string;
}

export class FrondClient {
  constructor(private readonly options: FrondClientOptions) {}

  private headers(): HeadersInit {
    const h: Record<string, string> = {
      "Content-Type": "application/json",
      Accept: "application/json",
    };
    if (this.options.bearerToken) {
      h.Authorization = \`Bearer \${this.options.bearerToken}\`;
    }
    if (this.options.apiKey) {
      h["X-Api-Key"] = this.options.apiKey;
    }
    return h;
  }

  async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await fetch(new URL(path, this.options.baseUrl), {
      method,
      headers: this.headers(),
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) {
      const text = await res.text();
      throw new Error(\`API error \${res.status}: \${text}\`);
    }
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  getHealth(): Promise<{ status: string }> {
    return this.request("GET", "/health");
  }

  createUser(body: { email: string; name: string }): Promise<{ id: string; email: string; name: string }> {
    return this.request("POST", "/users", body);
  }
}
`;

  const indexCode = `export * from "./client.js";\n`;

  await writeFile(path.join(outDir, "client.ts"), clientCode);
  await writeFile(path.join(outDir, "index.ts"), indexCode);
  await writeFile(
    path.join(outDir, "package.json"),
    JSON.stringify(
      {
        name: "@generated/frond-typescript-sdk",
        version: "0.1.0",
        type: "module",
        main: "./index.ts",
      },
      null,
      2,
    ),
  );
}

async function generatePythonSDK(outDir: string, openApiPath: string) {
  const clientCode = `"""Generated by Frond — do not edit manually."""

from __future__ import annotations

from typing import Any, Optional
import httpx


class FrondClient:
    def __init__(self, base_url: str, api_key: Optional[str] = None, bearer_token: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.bearer_token = bearer_token

    def _headers(self) -> dict[str, str]:
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if self.bearer_token:
            headers["Authorization"] = f"Bearer {self.bearer_token}"
        if self.api_key:
            headers["X-Api-Key"] = self.api_key
        return headers

    def request(self, method: str, path: str, json: Any | None = None) -> Any:
        with httpx.Client(base_url=self.base_url, headers=self._headers(), timeout=30.0) as client:
            response = client.request(method, path, json=json)
            response.raise_for_status()
            if response.status_code == 204:
                return None
            return response.json()

    def get_health(self) -> dict[str, str]:
        return self.request("GET", "/health")

    def create_user(self, email: str, name: str) -> dict[str, str]:
        return self.request("POST", "/users", json={"email": email, "name": name})
`;

  await writeFile(path.join(outDir, "client.py"), clientCode);
  await writeFile(path.join(outDir, "__init__.py"), `from .client import FrondClient\n`);
  await writeFile(
    path.join(outDir, "pyproject.toml"),
    `[project]\nname = "frond-python-sdk"\nversion = "0.1.0"\ndependencies = ["httpx>=0.27"]\n`,
  );
}
